pipeline {
  agent any
  
  stages {
    stage('Git fatch') {
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/s4616/spring-petclinic.git/',
          branch: 'main', credentialId: 'gitCredential'
      }
    }
    stage('Maven Build') {
      steps {
        echo 'Maven Build'
      }
    }
    stage('Docker Image') {
      steps {
        echo 'Docker Image'
      }
    }
    stage('Image Push') {
      steps {
        echo 'Image Push'
      }
    }
    stage('Codedeploy Workload ') {
      steps {
        echo 'Codedeploy Workload'
      }
    }
  }
}
